services:
  # Main Open Hateable application  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3000"  # Map external port 3001 to internal port 3000
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max-old-space-size=4096
      - FIRECRAWL_API_URL=http://firecrawl-api:3002
      - SANDBOX_SERVICE_URL=http://sandbox-service:3004
      - SANDBOX_PUBLIC_URL=http://localhost:3004
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/test-endpoint"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./sandboxes:/app/sandboxes  # Mount sandbox directory
      - ./data:/app/data  # Persistent data storage
    depends_on:
      - firecrawl-api
      - sandbox-service
    networks:
      - lovable-network

  # Containerized Sandbox Service
  sandbox-service:
    build:
      context: ./services/sandbox-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"  # Sandbox management API
    environment:
      - NODE_ENV=production
      - PORT=3004
    restart: unless-stopped
    volumes:
      - sandbox-data:/app/sandboxes  # Persistent sandbox storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lovable-network

  # Self-hosted Firecrawl Simple services with pydoll  
  pydoll-service:
    build:
      context: ./firecrawl-simple/apps/pydoll-service
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-10}
    networks:
      - lovable-network

  firecrawl-api:
    build:
      context: ./firecrawl-simple/apps/api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://firecrawl-redis:6379
      - REDIS_RATE_LIMIT_URL=redis://firecrawl-redis:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://pydoll-service:3003/scrape
      - PORT=3002
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE:-8}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY:-changeme-secure-key}
      - TEST_API_KEY=${TEST_API_KEY:-test-key}
      - HOST=0.0.0.0
      - LOGGING_LEVEL=${LOGGING_LEVEL:-info}
      - MAX_RAM=${MAX_RAM:-0.95}
      - MAX_CPU=${MAX_CPU:-0.95}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pydoll-service
      - firecrawl-redis
    command: ["pnpm", "run", "start:production"]
    networks:
      - lovable-network

  firecrawl-worker:
    build:
      context: ./firecrawl-simple/apps/api
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://firecrawl-redis:6379
      - REDIS_RATE_LIMIT_URL=redis://firecrawl-redis:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://pydoll-service:3003/scrape
      - PORT=3002
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE:-8}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY:-changeme-secure-key}
      - TEST_API_KEY=${TEST_API_KEY:-test-key}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - HOST=0.0.0.0
      - LOGGING_LEVEL=${LOGGING_LEVEL:-info}
      - MAX_RAM=${MAX_RAM:-0.95}
      - MAX_CPU=${MAX_CPU:-0.95}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pydoll-service
      - firecrawl-api
      - firecrawl-redis
    command: ["pnpm", "run", "workers"]
    networks:
      - lovable-network

  firecrawl-redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    networks:
      - lovable-network

volumes:
  firecrawl-data:
  sandbox-data:

networks:
  lovable-network:
    driver: bridge