FROM node:20-slim
WORKDIR /app
RUN apt-get update && apt-get install -y python3 make g++ zip && rm -rf /var/lib/apt/lists/*
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build
ENV NODE_ENV=production
EXPOSE 3000
EXPOSE 5173
CMD ["npm", "start"]
